feat: add const for contract status
mon-petit-placement/mpp-generali-client-bundle pull request #42
Opened 2023-11-03 13:59 UTC by 80r1an

2023-11-03 15:50 UTC, Celine68 approved these changes

2023-11-03 15:51 UTC, Celine68 requested changes

2023-11-03 15:51 UTC, Celine68 commented on Model/Situation.php
> +
public const

2023-11-13 09:40 UTC, oliviermpp approved these changes

2023-11-13 10:06 UTC, merged